spring.application.name=portfolio

server.port=8080

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${tenant-id}
spring.cloud.azure.active-directory.profile.environment.active-directory-endpoint=${active-directory-endpoint}
spring.cloud.azure.active-directory.credential.client-id=${client-id}
spring.cloud.azure.active-directory.credential.client-secret=${client-secret}