spring.application.name=portfolio

server.port=${APP_PORT}

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${TENANT_ID}
spring.cloud.azure.active-directory.profile.environment.active-directory-endpoint=${ACTIVE_DIRECTORY_ENDPOINT}
spring.cloud.azure.active-directory.credential.client-id=${CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${CLIENT_SECRET}

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL:false}

spring.session.redis.flush-mode=on-save
server.servlet.session.timeout=1800

spring.jmx.enabled=false

logging.level.com.mihashi_toshitaka.portfolio=${LOGGING_LEVEL:DEBUG}
logging.level.root=INFO
# logging.file.name=stdout