spring.application.name=portfolio

server.port=${APP_PORT}

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${TENANT_ID}
spring.cloud.azure.active-directory.profile.environment.active-directory-endpoint=${ACTIVE_DIRECTORY_ENDPOINT}
spring.cloud.azure.active-directory.credential.client-id=${CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${CLIENT_SECRET}

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL:false}

spring.session.redis.flush-mode=on-save
spring.threads.virtual.enabled=true
server.servlet.session.timeout=1800

management.endpoints.access.default=none
management.endpoints.web.exposure.include=health,info
management.endpoint.health.access=unrestricted
management.endpoint.info.access=read-only

server.error.include-stacktrace=never
server.error.include-message=never

spring.jmx.enabled=false

logging.level.com.mihashi-toshitaka.portfolio=${LOGGING_LEVEL:DEBUG}
logging.level.org.springframework.security=DEBUG
logging.level.com.azure.spring=DEBUG
logging.level.root=INFO
# logging.file.name=stdout
